baseURL: 'https://hugo.rmswing.de'
title: 'Rhein Main Swing Time'

ignoreFiles:
  - "src$"

defaultContentLanguage: de
languages:
  en:
    title: Rhein Main Swing Time
    weight: 2
    params:
      nav: Switch to English
  de:
    contentDir: content/de
    params:
      navigation:
        help: Zu Deutsch wechseln
    title: Rhein Main Swing Time
    weight: 1

module:
  mounts:
    - source: i18n
      target: i18n
    - source: i18n
      target: data
    - source: data
      target: data