baseURL: 'https://hugo.rmswing.de'
title: 'Rhein Main Swing Time'

defaultContentLanguage: de

languages:
  en:
    title: Rhein Main Swing Time
    weight: 2
    languageName: Switch to English
    contentDir: content/en
  de:
    title: Rhein Main Swing Time
    weight: 1
    contentDir: content/de
    languageName: Zu Deutsch wechseln

module:
  mounts:
    - source: i18n
      target: i18n
    - source: i18n
      target: data
    - source: data
      target: data
