baseURL: 'https://hugo.rmswing.de'
title: 'Rhein Main Swing Time'

params:
    googleMapsQuery: https://www.google.com/maps/search/

defaultContentLanguage: de
languages:
  en:
    title: Rhein Main Swing Time
    weight: 2
    languageName: Switch to English
    contentDir: content/en
  de:
    title: Rhein Main Swing Time
    weight: 1
    contentDir: content/de
    languageName: Zu Deutsch wechseln

module:
  mounts:
    - source: i18n
      target: i18n
    - source: i18n
      target: data
    - source: data
      target: data

security:
  enableInlineShortcodes: false
  exec:
    allow:
        - '^dart-sass-embedded$'
        - '^go$'
        - '^npx$'
        - '^postcss$'
        - '^babel$'
    osEnv:
        - '(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$'
  funcs:
    getenv:
        - '^HUGO_'
  http:
    methods:
        - '(?i)GET|POST'
    urls:
        - '.*'