# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Update and Build
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USER }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          script: |
            cd ${{ secrets.DEPLOYMENT_ROOT }}/${{ secrets.BASE_FOLDER }}
            git checkout --force main
            git fetch
            git reset --hard origin/main
            yarn install
            yarn prod
            chmod +x ./bin/hugo
            ./bin/hugo --ignoreCache --minify -d ${{ secrets.DEPLOYMENT_ROOT }}/frontend_hugo_dist_${{ github.run_number }}_${{ github.sha }}
      - name: Linking
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USER }}
          key: ${{ secrets.DEPLOYMENT_KEY }}
          script: |
            cd ${{ secrets.DEPLOYMENT_ROOT }}
            # rm ${{ secrets.DEPLOYMENT_ROOT }}/${{ secrets.PUBLIC_WEBROOT }}
            ln -s frontend_hugo_dist_${{ github.run_number }}_${{ github.sha }} ${{ secrets.PUBLIC_WEBROOT }}
            echo "Deleting old builds (keeping 10)"
            ls -tp | grep frontend_hugo_dist_ | grep -v '\$' | tail -n +10 | xargs -d '\n' -r rm -r --
